apiVersion: v1
kind: Namespace
metadata:
  name: #NAMESPACE
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: #APP_NAME
  namespace: #NAMESPACE
  labels:
    name: #APP_NAME
    app: #APP_NAME
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
    - group: core
      kind: Pods
    - group: apps
      kind: Deployment
    - group: route.openshift.io
      kind: Route
    - group: core
      kind: Service
  descriptor: {}
  selector:
    matchLabels:
      app: #APP_NAME
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: #APP_NAME
  namespace: #NAMESPACE
  generation: 1
  labels:
    app: #APP_NAME
spec:
  name: #APP_NAME
  channel: #NAMESPACE/helm-repo-artifactory
  packageFilter:
    version: #VERSION
  placement:
    placementRef:
      name: #APP_NAME-rule
      kind: PlacementRule
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: #APP_NAME-rule
  namespace: #NAMESPACE
  generation: 1
  labels:
    purpose: #APP_NAME
spec:
  clusterReplicas: 3
  clusterLabels:
    matchLabels:
      name: #CLUSTER
